all:
	javac -d classes *.java

run:
	java -cp classes org.ioopm.calculator.Calculator

testAST:
	java -cp classes org.ioopm.calculator.TestAST

testParser:
	java -cp classes org.ioopm.calculator.TestParser

clean:
	rm -rf classes
